# Generated by Django 4.0.8 on 2022-11-08 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=200)),
                ('annid', models.IntegerField(blank=True)),
                ('show', models.CharField(max_length=200)),
                ('opedin', models.CharField(max_length=25)),
                ('h720', models.URLField(blank=True, max_length=100)),
                ('h480', models.URLField(blank=True, max_length=100)),
                ('mp3', models.URLField(blank=True, max_length=100)),
            ],
        ),
    ]
