# Generated by Django 4.0.8 on 2022-11-13 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
